# Generated by Django 3.0 on 2022-09-19 10:40

from django.db import migrations


def migrate_db(apps, schema_editor):

    for profile in apps.get_model("oc_lettings_site", "Profile").objects.all():
        profile_lettings = apps.get_model("profiles", "Profile")(
            user=profile.user,
            favorite_city=profile.favorite_city,
        )
        profile_lettings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_db),
    ]
