version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: required packages
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          when: always
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: non regression tests
          command: |
            . venv/bin/activate
            pytest

  build_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: build and deploy to dockerhub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker build -t image_oc_lettings_site .
            docker tag image_oc_lettings_site $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
            docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1

  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - heroku/install
      # the create line is usually commented
      # if you need to re create the app, please comment the line out for one commit only.
      # heroku apps:create $HEROKU_APP_NAME --region eu --addons=heroku-postgresql
      # heroku config:set CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS -a $HEROKU_APP_NAME
      # heroku apps:create $HEROKU_APP_NAME --region eu --addons=heroku-postgresql
      # heroku heroku maintenance:on -a $HEROKU_APP_NAME
      # heroku heroku maintenance:off -a $HEROKU_APP_NAME
      - run:
          name: deploy container to heroku
          command: |
            set -x
            #heroku container:login
            docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
            # heroku apps:create $HEROKU_APP_NAME --region eu --addons=heroku-postgresql
            heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
            heroku config:set ALLOWED_HOSTS=$ALLOWED_HOSTS -a $HEROKU_APP_NAME
            heroku config:set DEBUG_COLLECTSTATIC=$DISABLE_COLLECTSTATIC  -a $HEROKU_APP_NAME
            heroku config:set DISABLE_COLLECTSTATIC=$DISABLE_COLLECTSTATIC -a $HEROKU_APP_NAME
            heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME
            heroku config:set ADMIN_USERNAME=$ADMIN_USERNAME -a $HEROKU_APP_NAME
            heroku config:set ADMIN_PASSWORD=$ADMIN_PASSWORD -a $HEROKU_APP_NAME
            heroku config:set ADMIN_EMAIL=$ADMIN_EMAIL -a $HEROKU_APP_NAME
            heroku container:push -a $HEROKU_APP_NAME web
            heroku container:release -a $HEROKU_APP_NAME web
            heroku run python manage.py migrate -a $HEROKU_APP_NAME
            heroku run python manage.py loaddata oclet.json -a $HEROKU_APP_NAME


workflows:
  main:
    jobs:
      - install-and-test
      - build_docker_image:
          requires:
            - install-and-test
      - deploy_docker_to_heroku:
          requires:
            - build_docker_image