version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: required packages
          command: |
            ls -l
            . venv/bin/activate
            pip install --user --no-cache-dir -r requirements.txt
          when: always
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: non-regression tests
          command: |
            . venv/bin/activate
            pytest


workflows:
  step1:
    jobs:
      - build-and-test
