version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: required packages
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          when: always
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: non regression tests
          command: |
            . venv/bin/activate
            pytest

  build_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: build and deploy to dockerhub
          command: |
            # echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            # docker build -t oc_lettings_site .
            # docker tag oc_lettings_site $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
            # docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
            docker image build --file=Dockerfile --tag=$DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1 .
            echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_LOGIN --password-stdin
            docker image push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1

  deploy_docker_to_heroku:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - heroku/install
      - run:
          name: deploy container to heroku
          command: |
            set -x
            heroku status
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku apps:create $HEROKU_APP_NAME --region eu --addons=heroku-postgresql
            
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py makemigrations -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py showmigrations -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py migrate -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py loaddata db_data.json -a $HEROKU_APP_NAME

workflows:
  main:
    jobs:
      - install-and-test
      - build_docker_image:
          requires:
            - install-and-test
      - deploy_docker_to_heroku:
          requires:
            - build_docker_image

