version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.10
    resource_class: small
    steps:
      - checkout
      - run:
          name: required packages
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          when: always
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: non regression tests
          command: |
            . venv/bin/activate
            pytest

  build_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: build and deploy to dockerhub
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker build -t image_oc_lettings_site .
            docker tag image_oc_lettings_site $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
            docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1

  deploy_docker_to_heroku:
  executor: heroku/default
  steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - heroku/install
    - run:
        name: deploy container to heroku
        command: |
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
          # (paste command line here)
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY -a $HEROKU_APP_NAME
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DEBUG=0 -a $HEROKU_APP_NAME
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py migrate -a $HEROKU_APP_NAME
          HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py loaddata data.json -a $HEROKU_APP_NAME

workflows:
  main:
    jobs:
      - install-and-test
      - build_docker_image:
          requires:
            - install-and-test
      - deploy_docker_to_heroku:
          requires:
            - build_docker_image