# Generated by Django 3.0 on 2022-09-19 10:46


from django.db import migrations


def migrate_db(apps, schema_editor):

    for address in apps.get_model("oc_lettings_site", "Address").objects.all():
        address_lettings = apps.get_model("lettings", "Address")(
            number=address.number,
            street=address.street,
            city=address.city,
            state=address.state,
            zip_code=address.zip_code,
            country_iso_code=address.country_iso_code,
        )
        address_lettings.save()
        for letting in apps.get_model("oc_lettings_site", "Letting").objects.filter(address=address):
            letting_lettings = apps.get_model("lettings", "Letting")(
                title=letting.title,
                address=address_lettings
            )
            letting_lettings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_db),
    ]
